//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTracker_c.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public string gamename { get; set; }
        public string venue { get; set; }
        public string hometeam { get; set; }
        public string awayteam { get; set; }
        public int hometeampoints { get; set; }
        public int awayteampoints { get; set; }
        public int attendance { get; set; }
        public string winningteam { get; set; }
        public System.DateTime dateplayed { get; set; }
    }
}
